# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20171115_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='seat',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
