# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurantlocation_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='seat',
        ),
    ]
